# Generated by Django 4.0.2 on 2022-04-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
