# Generated by Django 4.0.2 on 2022-04-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_delete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
