# Generated by Django 4.0.2 on 2022-04-02 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0024_alter_compra_data_alter_favorito_data_adicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 15, 42, 32, 774693), verbose_name='Data da compra'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='data_adicao',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 15, 42, 32, 774693), verbose_name='Data da Adição na lista'),
        ),
        migrations.AlterField(
            model_name='reclamacao',
            name='data_pergunta',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 15, 42, 32, 774693), verbose_name='Data Pergunta'),
        ),
    ]
